#!/bin/bash
## Begin Script
clear

## Install PEAR Packages
pear upgrade pear
pear install --onlyreqdeps DB
pear install --onlyreqdeps DB_DataObject
pear install --onlyreqdeps HTTP_Client
pear install --onlyreqdeps HTTP_Request
pear install --onlyreqdeps Mail
pear install --onlyreqdeps Mail_Mime
pear install --onlyreqdeps XML_Serializer-beta

# Install Smarty into PHP Include Directory
#PHPDIR=`pear config-get php_dir`
#SMARTYDIR="$PHPDIR/Smarty"
SMARTYDIR="/usr/share/pear/Smarty"
if [ ! -d $SMARTYDIR ]
then
    curl -O http://www.smarty.net/files/Smarty-3.1.19.tar.gz
    tar -zxf Smarty-3.1.19.tar.gz
    mkdir $SMARTYDIR
    mv Smarty-3.1.19/libs/* $SMARTYDIR
    rm Smarty-3.1.19.tar.gz
    rm -rf Smarty-3.1.19
fi

echo "Setup is now Complete"
